### ISSUE TITLE
Automatic Update Errors

### ISSUE THREAD

**Issue by ysndr** [nixexprs/nixpkgs#4]
The automatic update action will comment in this thread if updates failed.

**Comment by limeytexan** [comment]
@ysndr if I understand you correctly this issue is effectively a log file for the automation, but it's popping up as an exception in our project management efforts. My understanding is that the automation should be able to append to a closed issue (or reopen it?) just as easily as an open one, so I'll go ahead and close this to get it off our radar. If this breaks the automation then feel free to reopen.
